name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: xcodebuild test -project XCTestExample.xcodeproj/ -scheme XCTestExample -destination "platform=iOS Simulator,name=iPhone 12,OS=15.0" | xcpretty && exit ${PIPESTATUS[0]}
        #-resultBundlePath TestResults -sdk iphonesimulator 
        
      #- uses: kishikawakatsumi/xcresulttool@v1.3.0
      #  with:
      #    path: TestResults.xcresult
      #  if: success() || failure()
